version: "3.8"
services:
  firefox:
    image: selenium/node-firefox:4.6.0-20221104
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=90
      - SE_SESSION_REQUEST_TIMEOUT=1800000
      - SE_START_XVFB=true
  chrome:
    image: selenium/node-chrome:4.6.0-20221104
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=90
      - SE_SESSION_REQUEST_TIMEOUT=1800000
      - SE_START_XVFB=true

  selenium-hub:
    image: selenium/hub:4.6.0-20221104
    container_name: selenium-hub
    ports:
      - "127.0.0.1:4442:4442"
      - "127.0.0.1:4443:4443"
      - "127.0.0.1:4444:4444"
